const SHEETS = {
    FORM_RESPONSES: "Respostas do formulário 1",
    BASE_GASTPS: "BASE_GASTOS",
    FINANCEIRO: "FINANCEIRO",
    EVENTOS: "EVENTOS",
    CONFIG: "CONFIG",
};

const STATUS = {
    PENDENTE: "PENDENTE",
    PAGO : "PAGO",
    CANCELADO: "CANCELADO",
};

const CONFIG_KEYS = {
    ULTIMO_ID_GASTO: "ULTIMO_ID_GASTO",
    EMAIL_FINANCEIRO: "EMAIL_FINANCEIRO",
    NOME_EMPRESA: "NOME_EMPRESA",
};

